#include "state_space.h"
#include "state_space_detail.h"

#include "trademarks.h"

namespace lg {

namespace {

QString matlabMatrix(const std::vector<QStringList>& rows) {
    if (rows.empty()) {
        return QStringLiteral("[]");
    }
    QStringList matlabRows;
    matlabRows.reserve(static_cast<int>(rows.size()));
    for (const QStringList& row : rows) {
        matlabRows.push_back(row.join(QStringLiteral(", ")));
    }
    return QStringLiteral("[%1]").arg(matlabRows.join(QStringLiteral("; ")));
}

void appendMatrixAssignment(QStringList& lines, const QString& name,
                            const std::vector<QStringList>& rows) {
    if (rows.empty()) {
        return;
    }
    lines.push_back(QStringLiteral("%1 = %2;").arg(name, matlabMatrix(rows)));
}

}  // namespace

QString generateMatlabScript(const StateSpaceResult& result) {
    QStringList lines;
    lines.push_back(QStringLiteral("% State-space model generated by LGM"));
    lines.push_back(QStringLiteral("% %1").arg(app::mathWorksTrademarkNotice()));
    lines.push_back(QStringLiteral("%"));
    lines.push_back(QStringLiteral("% x_dot = A*x + B*u"));
    if (!ss::matrixIsZero(result.matrices.E)) {
        lines.back() += QStringLiteral(" + E*u_dot");
    }
    if (!result.matrices.C.empty()) {
        lines.push_back(QStringLiteral("% y = C*x + D*u"));
        if (!ss::matrixIsZero(result.matrices.F)) {
            lines.back() += QStringLiteral(" + F*u_dot");
        }
    }
    lines.push_back(QString());

    if (!result.matrices.parameters.isEmpty()) {
        lines.push_back(QStringLiteral("% Parameters (default value 1)"));
        for (const QString& param : result.matrices.parameters) {
            lines.push_back(QStringLiteral("%1 = 1;").arg(param));
        }
        lines.push_back(QString());
    }

    if (!result.stateVariables.isEmpty()) {
        lines.push_back(QStringLiteral("% States: %1")
                            .arg(result.stateVariables.join(QStringLiteral(", "))));
    }
    if (!result.inputs.isEmpty()) {
        const QStringList inputNames =
            result.inputLabels.isEmpty() ? result.inputs : result.inputLabels;
        lines.push_back(QStringLiteral("% Inputs: %1").arg(inputNames.join(QStringLiteral(", "))));
    }
    if (!result.outputs.isEmpty()) {
        const QStringList outputNames =
            result.outputLabels.isEmpty() ? result.outputs : result.outputLabels;
        lines.push_back(QStringLiteral("% Outputs: %1").arg(outputNames.join(QStringLiteral(", "))));
    }
    if (!result.stateVariables.isEmpty() || !result.inputs.isEmpty() || !result.outputs.isEmpty()) {
        lines.push_back(QString());
    }

    appendMatrixAssignment(lines, QStringLiteral("A"), result.matrices.A);
    appendMatrixAssignment(lines, QStringLiteral("B"), result.matrices.B);
    if (!ss::matrixIsZero(result.matrices.E)) {
        appendMatrixAssignment(lines, QStringLiteral("E"), result.matrices.E);
    }
    appendMatrixAssignment(lines, QStringLiteral("C"), result.matrices.C);
    appendMatrixAssignment(lines, QStringLiteral("D"), result.matrices.D);
    if (!ss::matrixIsZero(result.matrices.F)) {
        appendMatrixAssignment(lines, QStringLiteral("F"), result.matrices.F);
    }

    return lines.join(QStringLiteral("\n"));
}

}  // namespace lg
